# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=30)),
                ('supplier_mail_id', models.EmailField(max_length=30)),
                ('supplier_phone_number', models.CharField(max_length=15)),
                ('supplier_latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('supplier_longitude', models.DecimalField(decimal_places=6, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Systems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=30)),
                ('system_lead_time', models.DecimalField(decimal_places=3, max_digits=10)),
                ('system_volume_per_system', models.DecimalField(decimal_places=3, max_digits=10)),
                ('system_MOQ', models.IntegerField(default=100)),
                ('system_cost_per_system', models.DecimalField(decimal_places=3, max_digits=10)),
                ('order_requested', models.BooleanField(default=False)),
                ('ordered_quantity', models.IntegerField(default=100)),
                ('order_ETA', models.DecimalField(decimal_places=3, max_digits=10)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplierApp.Supplier')),
            ],
        ),
    ]
