# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Systems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsystem_1a', models.BooleanField(default=True)),
                ('subsystem_1b', models.BooleanField(default=True)),
                ('subsystem_1c', models.BooleanField(default=True)),
                ('subsystem_2a', models.BooleanField(default=True)),
                ('subsystem_2b', models.BooleanField(default=True)),
                ('subsystem_2c', models.BooleanField(default=True)),
                ('subsystem_3a', models.BooleanField(default=True)),
                ('subsystem_3b', models.BooleanField(default=True)),
                ('subsystem_3c', models.BooleanField(default=True)),
                ('subsystem_4a', models.BooleanField(default=True)),
                ('subsystem_4b', models.BooleanField(default=True)),
                ('subsystem_4c', models.BooleanField(default=True)),
                ('subsystem_5a', models.BooleanField(default=True)),
                ('subsystem_5b', models.BooleanField(default=True)),
                ('subsystem_5c', models.BooleanField(default=True)),
                ('subsystem_6a', models.BooleanField(default=True)),
                ('subsystem_6b', models.BooleanField(default=True)),
                ('subsystem_6c', models.BooleanField(default=True)),
                ('subsystem_7a', models.BooleanField(default=True)),
                ('subsystem_7b', models.BooleanField(default=True)),
                ('subsystem_7c', models.BooleanField(default=True)),
                ('system_1', models.BooleanField(default=True)),
                ('system_2', models.BooleanField(default=True)),
                ('system_3', models.BooleanField(default=True)),
                ('system_4', models.BooleanField(default=True)),
                ('system_5', models.BooleanField(default=True)),
                ('system_6', models.BooleanField(default=True)),
                ('system_7', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_mail_id', models.EmailField(max_length=30)),
                ('customer_phone_number', models.CharField(max_length=15)),
                ('customer_latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('customer_longitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('customer_purchase_date', models.DateTimeField()),
                ('distance_rode', models.DecimalField(decimal_places=2, max_digits=4)),
                ('battery_soh', models.DecimalField(decimal_places=2, max_digits=3)),
                ('service_status', models.IntegerField(default=1)),
                ('kms_at_previous_service', models.DecimalField(decimal_places=2, max_digits=4)),
                ('time_at_previous_service', models.DateTimeField()),
                ('service_requested', models.BooleanField(default=False)),
                ('problem_requested', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='systems',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeHome.Vehicle'),
        ),
    ]
