# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeHome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
