# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeHome', '0002_auto_20161121_0724'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Systems',
            new_name='System',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='battery_soh',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='distance_rode',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='kms_at_previous_service',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
