# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikeHome', '0003_auto_20161121_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='system_1',
        ),
        migrations.RemoveField(
            model_name='system',
            name='system_2',
        ),
        migrations.RemoveField(
            model_name='system',
            name='system_3',
        ),
        migrations.RemoveField(
            model_name='system',
            name='system_4',
        ),
        migrations.RemoveField(
            model_name='system',
            name='system_5',
        ),
        migrations.RemoveField(
            model_name='system',
            name='system_6',
        ),
        migrations.RemoveField(
            model_name='system',
            name='system_7',
        ),
    ]
