# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeHome', '0005_auto_20161121_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='supplier_1',
            field=models.CharField(choices=[('s1a', 'name#s1a'), ('s1b', 'name#s1b'), ('s1c', 'name#s1c')], default='s1a', max_length=2),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='supplier_2',
            field=models.CharField(choices=[('s2a', 'name#s2a'), ('s2b', 'name#s2b'), ('s2c', 'name#s2c')], default='s2a', max_length=2),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='supplier_3',
            field=models.CharField(choices=[('s3a', 'name#s3a'), ('s3b', 'name#s3b'), ('s3c', 'name#s3c')], default='s3a', max_length=2),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='supplier_4',
            field=models.CharField(choices=[('s4a', 'name#s4a'), ('s4b', 'name#s4b'), ('s4c', 'name#s4c')], default='s4a', max_length=2),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='supplier_5',
            field=models.CharField(choices=[('s5a', 'name#s5a'), ('s5b', 'name#s5b'), ('s5c', 'name#s5c')], default='s5a', max_length=2),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='supplier_6',
            field=models.CharField(choices=[('s6a', 'name#s6a'), ('s6b', 'name#s6b'), ('s6c', 'name#s6c')], default='s6a', max_length=2),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='supplier_7',
            field=models.CharField(choices=[('s7a', 'name#s7a'), ('s7b', 'name#s7b'), ('s7c', 'name#s7c')], default='s7a', max_length=2),
        ),
    ]
