# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikeHome', '0007_auto_20161128_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=20)),
                ('order_lead_time', models.DecimalField(decimal_places=3, max_digits=10)),
                ('order_volume_per_unit', models.DecimalField(decimal_places=3, max_digits=10)),
                ('order_MOQ', models.IntegerField(default=100)),
                ('order_cost_per_system', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ordered_quantity', models.IntegerField(default=100)),
                ('order_ETA', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SubSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsystem_name', models.CharField(max_length=30)),
                ('subsystem_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_name', models.CharField(max_length=20)),
                ('supplier_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('supplier_mail_id', models.EmailField(max_length=30)),
                ('supplier_phone_number', models.CharField(max_length=15)),
                ('supplier_latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('supplier_longitude', models.DecimalField(decimal_places=6, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('system_name', models.CharField(max_length=30)),
                ('system_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='subsystem_1a',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='subsystem_1b',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='subsystem_1c',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='subsystem_2a',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='subsystem_2b',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='subsystem_2c',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='subsystem_3a',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='subsystem_3b',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='subsystem_3c',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='subsystem_4a',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='subsystem_4b',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='subsystem_4c',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='subsystem_5a',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='subsystem_5b',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='subsystem_5c',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='subsystem_6a',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='subsystem_6b',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='subsystem_6c',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='subsystem_7a',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='subsystem_7b',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='subsystem_7c',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='system_1_supplier',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='system_2_supplier',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='system_3_supplier',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='system_4_supplier',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='system_5_supplier',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='system_6_supplier',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='system_7_supplier',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='system',
            field=models.ManyToManyField(to='bikeHome.System'),
        ),
        migrations.AddField(
            model_name='subsystem',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeHome.System'),
        ),
        migrations.AddField(
            model_name='batch',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeHome.Supplier'),
        ),
        migrations.AddField(
            model_name='batch',
            name='system',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bikeHome.System'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='supplier',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='bikeHome.Supplier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='system',
            field=models.OneToOneField(default=321, on_delete=django.db.models.deletion.CASCADE, to='bikeHome.System'),
            preserve_default=False,
        ),
    ]
