# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeHome', '0008_auto_20161130_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='system',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='system',
            field=models.ManyToManyField(to='bikeHome.System'),
        ),
    ]
