# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeHome', '0009_auto_20161130_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='id',
            field=models.AutoField(auto_created=True, default=1234, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='system',
            name='system_id',
            field=models.CharField(max_length=11),
        ),
    ]
