# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikeHome', '0011_auto_20161130_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='system_id',
            new_name='system_no',
        ),
    ]
