# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikeHome', '0013_auto_20161130_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='system',
        ),
        migrations.AddField(
            model_name='supplier',
            name='system',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='bikeHome.System'),
            preserve_default=False,
        ),
    ]
