# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikeHome', '0014_auto_20161130_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='supplier',
        ),
    ]
