# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikeHome', '0015_remove_vehicle_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='system',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='system',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
