# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikeHome', '0016_auto_20161130_0648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=20)),
                ('order_lead_time', models.DecimalField(decimal_places=3, max_digits=10)),
                ('order_volume_per_unit', models.DecimalField(decimal_places=3, max_digits=10)),
                ('order_MOQ', models.IntegerField(default=100)),
                ('order_cost_per_system', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ordered_quantity', models.IntegerField(default=100)),
                ('order_ETA', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_mail_id', models.EmailField(max_length=30)),
                ('customer_phone_number', models.CharField(max_length=15)),
                ('customer_latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('customer_longitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('customer_purchase_date', models.DateTimeField()),
                ('distance_rode', models.DecimalField(decimal_places=2, max_digits=6)),
                ('battery_soh', models.DecimalField(decimal_places=2, max_digits=5)),
                ('service_status', models.IntegerField(default=1)),
                ('kms_at_previous_service', models.DecimalField(decimal_places=2, max_digits=6)),
                ('time_at_previous_service', models.DateTimeField()),
                ('service_requested', models.BooleanField(default=False)),
                ('problem_requested', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='system',
            old_name='system_no',
            new_name='system_id',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='system',
        ),
        migrations.AddField(
            model_name='supplier',
            name='system',
            field=models.ManyToManyField(to='bikeHome.System'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeHome.System'),
        ),
        migrations.AddField(
            model_name='batch',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeHome.Supplier'),
        ),
        migrations.AddField(
            model_name='batch',
            name='system',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bikeHome.System'),
        ),
    ]
