# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeHome', '0018_auto_20161130_0704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name_plural': 'Batches'},
        ),
        migrations.RemoveField(
            model_name='batch',
            name='system',
        ),
        migrations.AddField(
            model_name='batch',
            name='system',
            field=models.ManyToManyField(to='bikeHome.System'),
        ),
    ]
