# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikeHome', '0019_auto_20161130_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='system',
        ),
        migrations.AddField(
            model_name='batch',
            name='system',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='bikeHome.System'),
            preserve_default=False,
        ),
    ]
