# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeHome', '0020_auto_20161130_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='system',
        ),
        migrations.AddField(
            model_name='batch',
            name='order_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='batch',
            field=models.ManyToManyField(to='bikeHome.Batch'),
        ),
    ]
