# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeHome', '0023_auto_20161130_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='subsystem_8a',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='subsystem_8b',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='subsystem_8c',
            field=models.BooleanField(default=True),
        ),
    ]
